name: Terraform Deploy

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if different
  workflow_dispatch:  # Allow manual triggering

env: # hard-code resource names
  AWS_REGION: us-east-1
  TFSTATE_KEY: application-signals/demo-applications
  TFSTATE_BUCKET: tfstate-0b6c1770-b7ce-423a-9b2d-781805b91dcc # prerequisite: manually create a bucket using  "aws s3 mb s3://tfstate-$(uuidgen | tr A-Z a-z)" and paste bucket name here.
  TFSTATE_REGION: us-east-1
  TF_VAR_cluster_name: app-signals-demo
  TF_VAR_cloudwatch_observability_addon_version: v3.6.0-eksbuild.2

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: terraform/eks
        run: |
          terraform init -backend-config="bucket=${{ env.TFSTATE_BUCKET }}" \
                        -backend-config="key=${{ env.TFSTATE_KEY }}" \
                        -backend-config="region=${{ env.TFSTATE_REGION }}"

      - name: Terraform Apply
        working-directory: terraform/eks
        run: terraform apply --auto-approve

      - name: Generate Software Dependency Topology
        uses: anchore/sbom-action@v0
        with:
          artifact-name: application-signals-demo.cyclonedx.json
          path: .
          output-file: './topology/application-signals-demo.cyclonedx.json'

      - name: Generate IaC Topology
        working-directory: terraform/eks
        run: terraform graph > ../../topology/terraform.graph.json
      
      - name: Publish Topology
        run: ls -l ./topology/
      
      - name: Build Docker images
        run: ./mvnw clean install -P buildDocker
        
      - name: Push Docker images to ECR
        run: |
          export ACCOUNT=$(aws sts get-caller-identity | jq .Account -r)
          export REGION=${{ env.AWS_REGION }}
          ./push-ecr.sh
      
      - name: Create kubeconfig directory
        run: mkdir -p ${{ github.workspace }}/.kube

      - name: Set KUBECONFIG environment variable
        run: echo KUBECONFIG="${{ github.workspace }}/.kube/config" >> $GITHUB_ENV

      - name: Set up kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.TF_VAR_cluster_name }} --region ${{ env.AWS_REGION }} --alias ${{ env.TF_VAR_cluster_name }}

      - name: Deploy Kubernetes resources
        run: |
          aws eks update-kubeconfig --name ${{ env.TF_VAR_cluster_name }} --kubeconfig ~/.kube/config --region ${{ env.AWS_REGION }} --alias ${{ env.TF_VAR_cluster_name }}
          ./scripts/eks/appsignals/tf-deploy-k8s-res.sh

      # - name: Create Canaries and SLOs
      #   run: |
      #     endpoint="http://$(kubectl get ingress -o json --output jsonpath='{.items[0].status.loadBalancer.ingress[0].hostname}')"
      #     cd scripts/eks/appsignals/
      #     ./create-canaries.sh ${{ env.AWS_REGION }} create $endpoint
      #     ./create-slo.sh $TF_VAR_cluster_name ${{ env.AWS_REGION }}

      - name: Output Application URL
        run: |
          endpoint="http://$(kubectl get ingress -o json --output jsonpath='{.items[0].status.loadBalancer.ingress[0].hostname}')"
          echo "Application is available at: $endpoint"
          echo "APPLICATION_URL=$endpoint" >> $GITHUB_ENV
